Feature: VoidLink
  Scenario: Get records put in active Void, from passive Voids
    Given there is a new Void "active"
    Given there is a new Void "passive0"
    Given there is a new Void "passive1"
    Given there is a new Minio server
    Given there is a new uplink-only VoidLink between "active" and "bucket"
    Given there is a new downlink-only VoidLink between "passive0" and "bucket"
    Given there is a new downlink-only VoidLink between "passive1" and "bucket"
    When I begin a transaction "txn0" in "active"
    When I open a cursor "cursor0" associated with keyspace "upper" and "txn0"
    When I open a cursor "cursor1" associated with keyspace "lower" and "txn0"
    When I put "key", "VALUE" using "cursor0"
    When I put "key", "value" using "cursor1"
    When I commit "txn0"
    When I wait for "1s"
    When I begin a read-only transaction "txn1" in "passive0"
    When I open a cursor "cursor2" associated with keyspace "upper" and "txn1"
    When I open a cursor "cursor3" associated with keyspace "lower" and "txn1"
    Then I should get "key", "VALUE" using "cursor2"
    Then I should get "key", "value" using "cursor3"
    When I begin a read-only transaction "txn2" in "passive1"
    When I open a cursor "cursor4" associated with keyspace "upper" and "txn2"
    When I open a cursor "cursor5" associated with keyspace "lower" and "txn2"
    Then I should get "key", "VALUE" using "cursor4"
    Then I should get "key", "value" using "cursor5"

  Scenario: Get records put in active Void from another active Void, both ways
    Given there is a new Void "active0"
    Given there is a new Void "active1"
    Given there is a new Minio server
    Given there is a new VoidLink between "active0" and "bucket"
    Given there is a new VoidLink between "active1" and "bucket"
    When I begin a transaction "txn0" in "active0"
    When I open a cursor "cursor0" associated with keyspace "upper" and "txn0"
    When I put "key", "VALUE" using "cursor0"
    When I commit "txn0"
    When I begin a transaction "txn1" in "active1"
    When I open a cursor "cursor1" associated with keyspace "lower" and "txn1"
    When I put "key", "value" using "cursor1"
    When I commit "txn1"
    When I wait for "1s"
    When I begin a read-only transaction "txn2" in "active0"
    When I open a cursor "cursor2" associated with keyspace "upper" and "txn2"
    When I open a cursor "cursor3" associated with keyspace "lower" and "txn2"
    Then I should get "key", "VALUE" using "cursor2"
    Then I should get "key", "value" using "cursor3"
    When I begin a read-only transaction "txn3" in "active1"
    When I open a cursor "cursor4" associated with keyspace "upper" and "txn3"
    When I open a cursor "cursor5" associated with keyspace "lower" and "txn3"
    Then I should get "key", "VALUE" using "cursor4"
    Then I should get "key", "value" using "cursor5"

  Scenario: Get records put in active Voids from other active Voids, three ways
    Given there is a new Void "active0"
    Given there is a new Void "active1"
    Given there is a new Void "active2"
    Given there is a new Minio server
    Given there is a new VoidLink between "active0" and "bucket"
    Given there is a new VoidLink between "active1" and "bucket"
    Given there is a new VoidLink between "active2" and "bucket"
    When I begin a transaction "txn0" in "active0"
    When I open a cursor "cursor0" associated with keyspace "upper" and "txn0"
    When I put "key", "VALUE" using "cursor0"
    When I commit "txn0"
    When I begin a transaction "txn1" in "active1"
    When I open a cursor "cursor1" associated with keyspace "lower" and "txn1"
    When I put "key", "value" using "cursor1"
    When I commit "txn1"
    When I begin a transaction "txn2" in "active2"
    When I open a cursor "cursor2" associated with keyspace "mixed" and "txn2"
    When I put "key", "vAlUe" using "cursor2"
    When I commit "txn2"
    When I wait for "1s"
    When I begin a read-only transaction "txn3" in "active0"
    When I open a cursor "cursor3" associated with keyspace "upper" and "txn3"
    When I open a cursor "cursor4" associated with keyspace "lower" and "txn3"
    When I open a cursor "cursor5" associated with keyspace "mixed" and "txn3"
    Then I should get "key", "VALUE" using "cursor3"
    Then I should get "key", "value" using "cursor4"
    Then I should get "key", "vAlUe" using "cursor5"
    When I begin a read-only transaction "txn4" in "active1"
    When I open a cursor "cursor6" associated with keyspace "upper" and "txn4"
    When I open a cursor "cursor7" associated with keyspace "lower" and "txn4"
    When I open a cursor "cursor8" associated with keyspace "mixed" and "txn4"
    Then I should get "key", "VALUE" using "cursor6"
    Then I should get "key", "value" using "cursor7"
    Then I should get "key", "vAlUe" using "cursor8"
    When I begin a read-only transaction "txn5" in "active2"
    When I open a cursor "cursor9" associated with keyspace "upper" and "txn5"
    When I open a cursor "cursorA" associated with keyspace "lower" and "txn5"
    When I open a cursor "cursorB" associated with keyspace "mixed" and "txn5"
    Then I should get "key", "VALUE" using "cursor9"
    Then I should get "key", "value" using "cursorA"
    Then I should get "key", "vAlUe" using "cursorB"

  Scenario: Get records put in active Void while passive Void was offline
    Given there is a new Void "active"
    Given there is a new Void "passive"
    Given there is a new Minio server
    Given there is a new uplink-only VoidLink between "active" and "bucket"
    When I begin a transaction "txn0" in "active"
    When I open a cursor "cursor0" associated with keyspace "space" and "txn0"
    When I put "key0", "value0" using "cursor0"
    When I put "key1", "value1" using "cursor0"
    When I commit "txn0"
    Given there is a new downlink-only VoidLink between "passive" and "bucket"
    When I wait for "1s"
    When I begin a read-only transaction "txn1" in "passive"
    When I open a cursor "cursor1" associated with keyspace "space" and "txn1"
    Then I should get "key0", "value0" using "cursor1"
    Then I should get "key1", "value1" using "cursor1"

  Scenario: Get records put in active Void while active Void was offline
    Given there is a new Void "active"
    Given there is a new Void "passive"
    Given there is a new Minio server
    Given there is a new downlink-only VoidLink between "passive" and "bucket"
    When I begin a transaction "txn0" in "active"
    When I open a cursor "cursor0" associated with keyspace "space" and "txn0"
    When I put "key0", "value0" using "cursor0"
    When I put "key1", "value1" using "cursor0"
    When I commit "txn0"
    Given there is a new uplink-only VoidLink between "active" and "bucket"
    When I wait for "1s"
    When I begin a read-only transaction "txn1" in "passive"
    When I open a cursor "cursor1" associated with keyspace "space" and "txn1"
    Then I should get "key0", "value0" using "cursor1"
    Then I should get "key1", "value1" using "cursor1"

  Scenario: Get records put in multi-active Voids while all Voids were offline
    Given there is a new Void "active0"
    Given there is a new Void "active1"
    Given there is a new Minio server
    When I begin a transaction "txn0" in "active0"
    When I open a cursor "cursor0" associated with keyspace "upper" and "txn0"
    When I put "key", "VALUE" using "cursor0"
    When I commit "txn0"
    When I begin a transaction "txn1" in "active1"
    When I open a cursor "cursor1" associated with keyspace "lower" and "txn1"
    When I put "key", "value" using "cursor1"
    When I commit "txn1"
    Given there is a new VoidLink between "active0" and "bucket"
    Given there is a new VoidLink between "active1" and "bucket"
    When I wait for "1s"
    When I begin a read-only transaction "txn2" in "active0"
    When I open a cursor "cursor2" associated with keyspace "upper" and "txn2"
    When I open a cursor "cursor3" associated with keyspace "lower" and "txn2"
    Then I should get "key", "VALUE" using "cursor2"
    Then I should get "key", "value" using "cursor3"
    When I begin a read-only transaction "txn3" in "active1"
    When I open a cursor "cursor4" associated with keyspace "upper" and "txn3"
    When I open a cursor "cursor5" associated with keyspace "lower" and "txn3"
    Then I should get "key", "VALUE" using "cursor4"
    Then I should get "key", "value" using "cursor5"

  Scenario: Get record put in one Void and deleted in another, from yet another
    Given there is a new Void "writer"
    Given there is a new Void "eraser"
    Given there is a new Void "reader"
    Given there is a new Minio server
    Given there is a new uplink-only VoidLink between "writer" and "bucket"
    Given there is a new VoidLink between "eraser" and "bucket"
    Given there is a new downlink-only VoidLink between "reader" and "bucket"
    When I begin a transaction "txn0" in "writer"
    When I open a cursor "cursor0" associated with keyspace "space" and "txn0"
    When I put "retain", "retain" using "cursor0"
    When I put "delete", "delete" using "cursor0"
    When I commit "txn0"
    When I wait for "1s"
    When I begin a transaction "txn1" in "eraser"
    When I open a cursor "cursor1" associated with keyspace "space" and "txn1"
    When I delete "delete" using "cursor1"
    When I commit "txn1"
    When I wait for "1s"
    When I begin a read-only transaction "txn2" in "reader"
    When I open a cursor "cursor2" associated with keyspace "space" and "txn2"
    Then I should get "retain", "retain" using "cursor2"
    Then getting "delete" using "cursor2" should not find
