Feature: VoidLink
  Scenario: Get records put in active Void, from passive Voids
    Given there is a new Void "active"
    Given there is a new Void "passive0"
    Given there is a new Void "passive1"
    Given there is a new Minio server
    Given there is a new VoidLink between "active" and "bucket"
    Given there is a new VoidLink between "passive0" and "bucket"
    Given there is a new VoidLink between "passive1" and "bucket"
    When I begin a transaction "txn0" in "active"
    When I open a cursor "cursor0" associated with keyspace "upper" and "txn0"
    When I open a cursor "cursor1" associated with keyspace "lower" and "txn0"
    When I put "key", "VALUE" using "cursor0"
    When I put "key", "value" using "cursor1"
    When I commit "txn0"
    When I wait for "1s"
    When I begin a read-only transaction "txn1" in "passive0"
    When I open a cursor "cursor2" associated with keyspace "upper" and "txn1"
    When I open a cursor "cursor3" associated with keyspace "lower" and "txn1"
    Then I should get "key", "VALUE" using "cursor2"
    Then I should get "key", "value" using "cursor3"
    When I begin a read-only transaction "txn2" in "passive1"
    When I open a cursor "cursor4" associated with keyspace "upper" and "txn2"
    When I open a cursor "cursor5" associated with keyspace "lower" and "txn2"
    Then I should get "key", "VALUE" using "cursor4"
    Then I should get "key", "value" using "cursor5"

  Scenario: Get records put in active Void from another active Void, both ways
    Given there is a new Void "active0"
    Given there is a new Void "active1"
    Given there is a new Minio server
    Given there is a new VoidLink between "active0" and "bucket"
    Given there is a new VoidLink between "active1" and "bucket"
    When I begin a transaction "txn0" in "active0"
    When I open a cursor "cursor0" associated with keyspace "upper" and "txn0"
    When I put "key", "VALUE" using "cursor0"
    When I commit "txn0"
    When I begin a transaction "txn1" in "active1"
    When I open a cursor "cursor1" associated with keyspace "lower" and "txn1"
    When I put "key", "value" using "cursor1"
    When I commit "txn1"
    When I wait for "1s"
    When I begin a read-only transaction "txn2" in "active0"
    When I open a cursor "cursor2" associated with keyspace "upper" and "txn2"
    When I open a cursor "cursor3" associated with keyspace "lower" and "txn2"
    Then I should get "key", "VALUE" using "cursor2"
    Then I should get "key", "value" using "cursor3"
    When I begin a read-only transaction "txn3" in "active1"
    When I open a cursor "cursor4" associated with keyspace "upper" and "txn3"
    When I open a cursor "cursor5" associated with keyspace "lower" and "txn3"
    Then I should get "key", "VALUE" using "cursor4"
    Then I should get "key", "value" using "cursor5"
