Feature: Node
  Scenario: Put key-value record into root Node, and then Get
    Given there is a new root Node "root"
    When I Put "key", "value" into "root"
    Then I should Get "key", "value" from "root"
    When I open a new cursor "cursor" at "root"
    Then I should get "key", "value" next from "cursor"
    Then getting next from "cursor" should not find

  Scenario: Get key-value record not yet Put
    Given there is a new root Node "root"
    Then Get-ting "key" from "root" should not find
    When I open a new cursor "cursor" at "root"
    Then getting next from "cursor" should not find

  Scenario: Put key-value records into root Node, causing overflow (2 levels)
    Given there is a new root Node "root"
    When I Put "key0", "value0" into "root"
    When I Put "key1", "value1" into "root"
    When I Put "key2", "value2" into "root"
    When I Put "key3", "value3" into "root"
    When I Put "key4", "value4" into "root"
    When I Put "key5", "value5" into "root"
    When I Put "key6", "value6" into "root"
    Then I should Get "key0", "value0" from "root"
    Then I should Get "key1", "value1" from "root"
    Then I should Get "key2", "value2" from "root"
    Then I should Get "key3", "value3" from "root"
    Then I should Get "key4", "value4" from "root"
    Then I should Get "key5", "value5" from "root"
    Then I should Get "key6", "value6" from "root"
    When I open a new cursor "cursor" at "root"
    Then I should get "key0", "value0" next from "cursor"
    Then I should get "key1", "value1" next from "cursor"
    Then I should get "key2", "value2" next from "cursor"
    Then I should get "key3", "value3" next from "cursor"
    Then I should get "key4", "value4" next from "cursor"
    Then I should get "key5", "value5" next from "cursor"
    Then I should get "key6", "value6" next from "cursor"
    Then getting next from "cursor" should not find

  Scenario: Put key-value records into root Node, causing overflow (3 levels)
    Given there is a new root Node "root"
    When I Put "key00", "value00" into "root"
    When I Put "key01", "value01" into "root"
    When I Put "key02", "value02" into "root"
    When I Put "key03", "value03" into "root"
    When I Put "key04", "value04" into "root"
    When I Put "key05", "value05" into "root"
    When I Put "key06", "value06" into "root"
    When I Put "key07", "value07" into "root"
    When I Put "key08", "value08" into "root"
    When I Put "key09", "value09" into "root"
    When I Put "key10", "value10" into "root"
    When I Put "key11", "value11" into "root"
    When I Put "key12", "value12" into "root"
    When I Put "key13", "value13" into "root"
    When I Put "key14", "value14" into "root"
    When I Put "key15", "value15" into "root"
    When I Put "key16", "value16" into "root"
    When I Put "key17", "value17" into "root"
    When I Put "key18", "value18" into "root"
    When I Put "key19", "value19" into "root"
    When I Put "key20", "value20" into "root"
    When I Put "key21", "value21" into "root"
    When I Put "key22", "value22" into "root"
    When I Put "key23", "value23" into "root"
    When I Put "key24", "value24" into "root"
    Then I should Get "key00", "value00" from "root"
    Then I should Get "key01", "value01" from "root"
    Then I should Get "key02", "value02" from "root"
    Then I should Get "key03", "value03" from "root"
    Then I should Get "key04", "value04" from "root"
    Then I should Get "key05", "value05" from "root"
    Then I should Get "key06", "value06" from "root"
    Then I should Get "key07", "value07" from "root"
    Then I should Get "key08", "value08" from "root"
    Then I should Get "key09", "value09" from "root"
    Then I should Get "key10", "value10" from "root"
    Then I should Get "key11", "value11" from "root"
    Then I should Get "key12", "value12" from "root"
    Then I should Get "key13", "value13" from "root"
    Then I should Get "key14", "value14" from "root"
    Then I should Get "key15", "value15" from "root"
    Then I should Get "key16", "value16" from "root"
    Then I should Get "key17", "value17" from "root"
    Then I should Get "key18", "value18" from "root"
    Then I should Get "key19", "value19" from "root"
    Then I should Get "key20", "value20" from "root"
    Then I should Get "key21", "value21" from "root"
    Then I should Get "key22", "value22" from "root"
    Then I should Get "key23", "value23" from "root"
    Then I should Get "key24", "value24" from "root"
    When I open a new cursor "cursor" at "root"
    Then I should get "key00", "value00" next from "cursor"
    Then I should get "key01", "value01" next from "cursor"
    Then I should get "key02", "value02" next from "cursor"
    Then I should get "key03", "value03" next from "cursor"
    Then I should get "key04", "value04" next from "cursor"
    Then I should get "key05", "value05" next from "cursor"
    Then I should get "key06", "value06" next from "cursor"
    Then I should get "key07", "value07" next from "cursor"
    Then I should get "key08", "value08" next from "cursor"
    Then I should get "key09", "value09" next from "cursor"
    Then I should get "key10", "value10" next from "cursor"
    Then I should get "key11", "value11" next from "cursor"
    Then I should get "key12", "value12" next from "cursor"
    Then I should get "key13", "value13" next from "cursor"
    Then I should get "key14", "value14" next from "cursor"
    Then I should get "key15", "value15" next from "cursor"
    Then I should get "key16", "value16" next from "cursor"
    Then I should get "key17", "value17" next from "cursor"
    Then I should get "key18", "value18" next from "cursor"
    Then I should get "key19", "value19" next from "cursor"
    Then I should get "key20", "value20" next from "cursor"
    Then I should get "key21", "value21" next from "cursor"
    Then I should get "key22", "value22" next from "cursor"
    Then I should get "key23", "value23" next from "cursor"
    Then I should get "key24", "value24" next from "cursor"
    Then getting next from "cursor" should not find

  Scenario: Del key-value record from root Node, and then Get
    Given there is a new root Node "root"
    When I Put "key", "value" into "root"
    When I Del "key" from "root"
    Then Get-ting "key" from "root" should not find

  Scenario: Del key-value record from root Node, causing underflow (take right)
    Given there is a new root Node "root"
    When I Put "key0", "value0" into "root"
    When I Put "key1", "value1" into "root"
    When I Put "key2", "value2" into "root"
    When I Put "key3", "value3" into "root"
    When I Put "key4", "value4" into "root"
    When I Put "key5", "value5" into "root"
    When I Put "key6", "value6" into "root"
    When I Del "key0" from "root"
    Then Get-ting "key0" from "root" should not find
    Then I should Get "key1", "value1" from "root"
    Then I should Get "key2", "value2" from "root"
    Then I should Get "key3", "value3" from "root"
    Then I should Get "key4", "value4" from "root"
    Then I should Get "key5", "value5" from "root"
    Then I should Get "key6", "value6" from "root"
    When I open a new cursor "cursor" at "root"
    Then I should get "key1", "value1" next from "cursor"
    Then I should get "key2", "value2" next from "cursor"
    Then I should get "key3", "value3" next from "cursor"
    Then I should get "key4", "value4" next from "cursor"
    Then I should get "key5", "value5" next from "cursor"
    Then I should get "key6", "value6" next from "cursor"
    Then getting next from "cursor" should not find

  Scenario: Del key-value record from root Node, causing underflow (take left)
    Given there is a new root Node "root"
    When I Put "key00", "value00" into "root"
    When I Put "key10", "value10" into "root"
    When I Put "key20", "value20" into "root"
    When I Put "key30", "value30" into "root"
    When I Put "key40", "value40" into "root"
    When I Put "key50", "value50" into "root"
    When I Put "key60", "value60" into "root"
    When I Put "key15", "value15" into "root"
    When I Del "key60" from "root"
    When I Del "key50" from "root"
    Then I should Get "key00", "value00" from "root"
    Then I should Get "key10", "value10" from "root"
    Then I should Get "key15", "value15" from "root"
    Then I should Get "key20", "value20" from "root"
    Then I should Get "key30", "value30" from "root"
    Then I should Get "key40", "value40" from "root"
    Then Get-ting "key50" from "root" should not find
    Then Get-ting "key60" from "root" should not find
    When I open a new cursor "cursor" at "root"
    Then I should get "key00", "value00" next from "cursor"
    Then I should get "key10", "value10" next from "cursor"
    Then I should get "key15", "value15" next from "cursor"
    Then I should get "key20", "value20" next from "cursor"
    Then I should get "key30", "value30" next from "cursor"
    Then I should get "key40", "value40" next from "cursor"
    Then getting next from "cursor" should not find

  Scenario: Del key-value record from root Node, causing underflow (merge right)
    Given there is a new root Node "root"
    When I Put "key0", "value0" into "root"
    When I Put "key1", "value1" into "root"
    When I Put "key2", "value2" into "root"
    When I Put "key3", "value3" into "root"
    When I Put "key4", "value4" into "root"
    When I Put "key5", "value5" into "root"
    When I Put "key6", "value6" into "root"
    When I Del "key6" from "root"
    When I Del "key0" from "root"
    Then Get-ting "key0" from "root" should not find
    Then I should Get "key1", "value1" from "root"
    Then I should Get "key2", "value2" from "root"
    Then I should Get "key3", "value3" from "root"
    Then I should Get "key4", "value4" from "root"
    Then I should Get "key5", "value5" from "root"
    Then Get-ting "key6" from "root" should not find
    When I open a new cursor "cursor" at "root"
    Then I should get "key1", "value1" next from "cursor"
    Then I should get "key2", "value2" next from "cursor"
    Then I should get "key3", "value3" next from "cursor"
    Then I should get "key4", "value4" next from "cursor"
    Then I should get "key5", "value5" next from "cursor"
    Then getting next from "cursor" should not find

  Scenario: Del key-value record from root Node, causing underflow (merge left)
    Given there is a new root Node "root"
    When I Put "key0", "value0" into "root"
    When I Put "key1", "value1" into "root"
    When I Put "key2", "value2" into "root"
    When I Put "key3", "value3" into "root"
    When I Put "key4", "value4" into "root"
    When I Put "key5", "value5" into "root"
    When I Put "key6", "value6" into "root"
    When I Put "key7", "value7" into "root"
    When I Put "key8", "value8" into "root"
    When I Put "key9", "value9" into "root"
    When I Del "key9" from "root"
    When I Del "key4" from "root"
    Then I should Get "key0", "value0" from "root"
    Then I should Get "key1", "value1" from "root"
    Then I should Get "key2", "value2" from "root"
    Then I should Get "key3", "value3" from "root"
    Then Get-ting "key4" from "root" should not find
    Then I should Get "key5", "value5" from "root"
    Then I should Get "key6", "value6" from "root"
    Then I should Get "key7", "value7" from "root"
    Then I should Get "key8", "value8" from "root"
    Then Get-ting "key9" from "root" should not find
    When I open a new cursor "cursor" at "root"
    Then I should get "key0", "value0" next from "cursor"
    Then I should get "key1", "value1" next from "cursor"
    Then I should get "key2", "value2" next from "cursor"
    Then I should get "key3", "value3" next from "cursor"
    Then I should get "key5", "value5" next from "cursor"
    Then I should get "key6", "value6" next from "cursor"
    Then I should get "key7", "value7" next from "cursor"
    Then I should get "key8", "value8" next from "cursor"
    Then getting next from "cursor" should not find
