Feature: Tree
  Scenario: Put key-value record, and then get
    Given there is a new tree "tree"
    When I put "key", "value" into "tree"
    Then I should get "key", "value" from "tree"
    When I open a new cursor "cursor" at the root of "tree"
    Then I should get "key", "value" next from "cursor"
    Then getting next from "cursor" should not find

  Scenario: Get key-value record not yet put
    Given there is a new tree "tree"
    Then getting "key" from "tree" should not find
    When I open a new cursor "cursor" at the root of "tree"
    Then getting next from "cursor" should not find

  Scenario: Put key-value records into tree, causing overflow (2 levels)
    Given there is a new tree "tree"
    When I put "key0", "value0" into "tree"
    When I put "key1", "value1" into "tree"
    When I put "key2", "value2" into "tree"
    When I put "key3", "value3" into "tree"
    When I put "key4", "value4" into "tree"
    When I put "key5", "value5" into "tree"
    When I put "key6", "value6" into "tree"
    Then I should get "key0", "value0" from "tree"
    Then I should get "key1", "value1" from "tree"
    Then I should get "key2", "value2" from "tree"
    Then I should get "key3", "value3" from "tree"
    Then I should get "key4", "value4" from "tree"
    Then I should get "key5", "value5" from "tree"
    Then I should get "key6", "value6" from "tree"
    When I open a new cursor "cursor" at the root of "tree"
    Then I should get "key0", "value0" next from "cursor"
    Then I should get "key1", "value1" next from "cursor"
    Then I should get "key2", "value2" next from "cursor"
    Then I should get "key3", "value3" next from "cursor"
    Then I should get "key4", "value4" next from "cursor"
    Then I should get "key5", "value5" next from "cursor"
    Then I should get "key6", "value6" next from "cursor"
    Then getting next from "cursor" should not find

  Scenario: Put key-value records into tree, causing overflow (3 levels)
    Given there is a new tree "tree"
    When I put "key00", "value00" into "tree"
    When I put "key01", "value01" into "tree"
    When I put "key02", "value02" into "tree"
    When I put "key03", "value03" into "tree"
    When I put "key04", "value04" into "tree"
    When I put "key05", "value05" into "tree"
    When I put "key06", "value06" into "tree"
    When I put "key07", "value07" into "tree"
    When I put "key08", "value08" into "tree"
    When I put "key09", "value09" into "tree"
    When I put "key10", "value10" into "tree"
    When I put "key11", "value11" into "tree"
    When I put "key12", "value12" into "tree"
    When I put "key13", "value13" into "tree"
    When I put "key14", "value14" into "tree"
    When I put "key15", "value15" into "tree"
    When I put "key16", "value16" into "tree"
    When I put "key17", "value17" into "tree"
    When I put "key18", "value18" into "tree"
    When I put "key19", "value19" into "tree"
    When I put "key20", "value20" into "tree"
    When I put "key21", "value21" into "tree"
    When I put "key22", "value22" into "tree"
    When I put "key23", "value23" into "tree"
    When I put "key24", "value24" into "tree"
    Then I should get "key00", "value00" from "tree"
    Then I should get "key01", "value01" from "tree"
    Then I should get "key02", "value02" from "tree"
    Then I should get "key03", "value03" from "tree"
    Then I should get "key04", "value04" from "tree"
    Then I should get "key05", "value05" from "tree"
    Then I should get "key06", "value06" from "tree"
    Then I should get "key07", "value07" from "tree"
    Then I should get "key08", "value08" from "tree"
    Then I should get "key09", "value09" from "tree"
    Then I should get "key10", "value10" from "tree"
    Then I should get "key11", "value11" from "tree"
    Then I should get "key12", "value12" from "tree"
    Then I should get "key13", "value13" from "tree"
    Then I should get "key14", "value14" from "tree"
    Then I should get "key15", "value15" from "tree"
    Then I should get "key16", "value16" from "tree"
    Then I should get "key17", "value17" from "tree"
    Then I should get "key18", "value18" from "tree"
    Then I should get "key19", "value19" from "tree"
    Then I should get "key20", "value20" from "tree"
    Then I should get "key21", "value21" from "tree"
    Then I should get "key22", "value22" from "tree"
    Then I should get "key23", "value23" from "tree"
    Then I should get "key24", "value24" from "tree"
    When I open a new cursor "cursor" at the root of "tree"
    Then I should get "key00", "value00" next from "cursor"
    Then I should get "key01", "value01" next from "cursor"
    Then I should get "key02", "value02" next from "cursor"
    Then I should get "key03", "value03" next from "cursor"
    Then I should get "key04", "value04" next from "cursor"
    Then I should get "key05", "value05" next from "cursor"
    Then I should get "key06", "value06" next from "cursor"
    Then I should get "key07", "value07" next from "cursor"
    Then I should get "key08", "value08" next from "cursor"
    Then I should get "key09", "value09" next from "cursor"
    Then I should get "key10", "value10" next from "cursor"
    Then I should get "key11", "value11" next from "cursor"
    Then I should get "key12", "value12" next from "cursor"
    Then I should get "key13", "value13" next from "cursor"
    Then I should get "key14", "value14" next from "cursor"
    Then I should get "key15", "value15" next from "cursor"
    Then I should get "key16", "value16" next from "cursor"
    Then I should get "key17", "value17" next from "cursor"
    Then I should get "key18", "value18" next from "cursor"
    Then I should get "key19", "value19" next from "cursor"
    Then I should get "key20", "value20" next from "cursor"
    Then I should get "key21", "value21" next from "cursor"
    Then I should get "key22", "value22" next from "cursor"
    Then I should get "key23", "value23" next from "cursor"
    Then I should get "key24", "value24" next from "cursor"
    Then getting next from "cursor" should not find

  Scenario: Delete key-value record from tree, and then get
    Given there is a new tree "tree"
    When I put "key", "value" into "tree"
    When I delete "key" from "tree"
    Then getting "key" from "tree" should not find

  Scenario: Delete key-value record from tree, causing underflow (take right)
    Given there is a new tree "tree"
    When I put "key0", "value0" into "tree"
    When I put "key1", "value1" into "tree"
    When I put "key2", "value2" into "tree"
    When I put "key3", "value3" into "tree"
    When I put "key4", "value4" into "tree"
    When I put "key5", "value5" into "tree"
    When I put "key6", "value6" into "tree"
    When I delete "key0" from "tree"
    Then getting "key0" from "tree" should not find
    Then I should get "key1", "value1" from "tree"
    Then I should get "key2", "value2" from "tree"
    Then I should get "key3", "value3" from "tree"
    Then I should get "key4", "value4" from "tree"
    Then I should get "key5", "value5" from "tree"
    Then I should get "key6", "value6" from "tree"
    When I open a new cursor "cursor" at the root of "tree"
    Then I should get "key1", "value1" next from "cursor"
    Then I should get "key2", "value2" next from "cursor"
    Then I should get "key3", "value3" next from "cursor"
    Then I should get "key4", "value4" next from "cursor"
    Then I should get "key5", "value5" next from "cursor"
    Then I should get "key6", "value6" next from "cursor"
    Then getting next from "cursor" should not find

  Scenario: Delete key-value record from tree, causing underflow (take left)
    Given there is a new tree "tree"
    When I put "key00", "value00" into "tree"
    When I put "key10", "value10" into "tree"
    When I put "key20", "value20" into "tree"
    When I put "key30", "value30" into "tree"
    When I put "key40", "value40" into "tree"
    When I put "key50", "value50" into "tree"
    When I put "key60", "value60" into "tree"
    When I put "key15", "value15" into "tree"
    When I delete "key60" from "tree"
    When I delete "key50" from "tree"
    Then I should get "key00", "value00" from "tree"
    Then I should get "key10", "value10" from "tree"
    Then I should get "key15", "value15" from "tree"
    Then I should get "key20", "value20" from "tree"
    Then I should get "key30", "value30" from "tree"
    Then I should get "key40", "value40" from "tree"
    Then getting "key50" from "tree" should not find
    Then getting "key60" from "tree" should not find
    When I open a new cursor "cursor" at the root of "tree"
    Then I should get "key00", "value00" next from "cursor"
    Then I should get "key10", "value10" next from "cursor"
    Then I should get "key15", "value15" next from "cursor"
    Then I should get "key20", "value20" next from "cursor"
    Then I should get "key30", "value30" next from "cursor"
    Then I should get "key40", "value40" next from "cursor"
    Then getting next from "cursor" should not find

  Scenario: Delete key-value record from tree, causing underflow (merge right)
    Given there is a new tree "tree"
    When I put "key0", "value0" into "tree"
    When I put "key1", "value1" into "tree"
    When I put "key2", "value2" into "tree"
    When I put "key3", "value3" into "tree"
    When I put "key4", "value4" into "tree"
    When I put "key5", "value5" into "tree"
    When I put "key6", "value6" into "tree"
    When I delete "key6" from "tree"
    When I delete "key0" from "tree"
    Then getting "key0" from "tree" should not find
    Then I should get "key1", "value1" from "tree"
    Then I should get "key2", "value2" from "tree"
    Then I should get "key3", "value3" from "tree"
    Then I should get "key4", "value4" from "tree"
    Then I should get "key5", "value5" from "tree"
    Then getting "key6" from "tree" should not find
    When I open a new cursor "cursor" at the root of "tree"
    Then I should get "key1", "value1" next from "cursor"
    Then I should get "key2", "value2" next from "cursor"
    Then I should get "key3", "value3" next from "cursor"
    Then I should get "key4", "value4" next from "cursor"
    Then I should get "key5", "value5" next from "cursor"
    Then getting next from "cursor" should not find

  Scenario: Delete key-value record from tree, causing underflow (merge left)
    Given there is a new tree "tree"
    When I put "key0", "value0" into "tree"
    When I put "key1", "value1" into "tree"
    When I put "key2", "value2" into "tree"
    When I put "key3", "value3" into "tree"
    When I put "key4", "value4" into "tree"
    When I put "key5", "value5" into "tree"
    When I put "key6", "value6" into "tree"
    When I put "key7", "value7" into "tree"
    When I put "key8", "value8" into "tree"
    When I put "key9", "value9" into "tree"
    When I delete "key9" from "tree"
    When I delete "key4" from "tree"
    Then I should get "key0", "value0" from "tree"
    Then I should get "key1", "value1" from "tree"
    Then I should get "key2", "value2" from "tree"
    Then I should get "key3", "value3" from "tree"
    Then getting "key4" from "tree" should not find
    Then I should get "key5", "value5" from "tree"
    Then I should get "key6", "value6" from "tree"
    Then I should get "key7", "value7" from "tree"
    Then I should get "key8", "value8" from "tree"
    Then getting "key9" from "tree" should not find
    When I open a new cursor "cursor" at the root of "tree"
    Then I should get "key0", "value0" next from "cursor"
    Then I should get "key1", "value1" next from "cursor"
    Then I should get "key2", "value2" next from "cursor"
    Then I should get "key3", "value3" next from "cursor"
    Then I should get "key5", "value5" next from "cursor"
    Then I should get "key6", "value6" next from "cursor"
    Then I should get "key7", "value7" next from "cursor"
    Then I should get "key8", "value8" next from "cursor"
    Then getting next from "cursor" should not find
